version: '3.8'

services:
  app:
    image: travel-booking-web-app-dev:latest
    container_name: travel-booking-web-app-dev
    environment:
      # Database Configuration (через SSH tunnel)
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      # Next.js Environment
      - NODE_ENV=${NODE_ENV}
      # Telegram Bot Configuration
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_NAME=${BOT_NAME}
      # JWT Authentication
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped