version: '3.8'

services:
  app:
    image: travel-booking-web-app.cr.cloud.ru/travel-booking-web-app
    container_name: travel-booking-web-app
    network_mode: "host"
    environment:
      # Database Configuration (подключение к PostgreSQL на хосте)
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=localhost
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      # Next.js Environment
      - NODE_ENV=${NODE_ENV}
      # Telegram Bot Configuration
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_NAME=${BOT_NAME}
      # JWT Authentication
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      # Prisma Logging Configuration
      - PRISMA_LOG_LEVELS=${PRISMA_LOG_LEVELS}
      # Cloud.ru artifact registry
      - CLOUD_RU_KEY_ID=${CLOUD_RU_KEY_ID}
      - CLOUD_RU_KEY_SECRET=${CLOUD_RU_KEY_SECRET}
    env_file:
      - .env
    restart: unless-stopped