import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Footer} from "@/components/Footer";
import {AuthProvider} from "@/contexts/AuthContext";
import {CurrentLocation} from "@/components/location/current/CurrentLocation";
import {TelegramClosingHandler} from "@/components/TelegramClosingHandler";
import {ErrorBoundary} from "@/components/ErrorBoundary";
import {LogsProvider} from "@/components/LogsProvider";

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <ErrorBoundary>
          <LogsProvider>
            <AuthProvider>
              <TelegramClosingHandler />
              <CurrentLocation/>
              <main className="pb-20">
                {children}
              </main>
              <Footer />
            </AuthProvider>
          </LogsProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
