name: DEV travel-booking-web-app docker image build, push and deploy

on:
  push:
    branches:
      - dev

jobs:
  build-nextjs-app:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

  build-and-push-docker-image:
    needs: build-nextjs-app
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ARTIFACT_REGISTRY_URI }}
          username: ${{ secrets.CLOUD_RU_KEY_ID }}
          password: ${{ secrets.CLOUD_RU_KEY_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.ARTIFACT_REGISTRY_URI }}/${{ secrets.ARTIFACT_REGISTRY_NAME }}:latest

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: [build-nextjs-app, build-and-push-docker-image]
    environment: dev
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            cd ${{ vars.DEPLOY_DIRECTORY_PATH }}
            
            # Запускаем prepare.sh (если нужно)
            if [ ! -f ".env" ] || [ ! -f "${{ vars.DOCKER_COMPOSE_FILE_NAME }}" ]; then
              echo "⚠️  prepare.sh не выполнен или файлы не найдены"
              echo "Запускаем prepare.sh..."
              chmod +x prepare.sh
              ./prepare.sh
            else
              echo "✅ prepare.sh уже выполнен, пропускаем"
            fi
            
            # Запускаем run.sh для деплоя
            echo "🚀 Запускаем деплой..."
            chmod +x run.sh
            ./run.sh
            
            echo "🎉 Деплой завершен успешно!"