name: tg-bot-notifier-server docker image build and push

on:
  push:
    branches:
      - master
      - deploy
env:
  CLOUD_RU_ARTIFACT_REGISTRY_URI: travel-booking-web-app.cr.cloud.ru

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CLOUD_RU_ARTIFACT_REGISTRY_URI }}
          username: ${{ secrets.CLOUD_RU_KEY_ID }}
          password: ${{ secrets.CLOUD_RU_KEY_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.CLOUD_RU_ARTIFACT_REGISTRY_URI }}/travel-booking-web-app:latest